/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/AppAlert.vue')['default']
    CopiableCode: typeof import('./src/components/CopiableCode.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    RecommendedClientFooter: typeof import('./src/components/RecommendedClientFooter.vue')['default']
    RegistrationStatusCard: typeof import('./src/components/RegistrationStatusCard.vue')['default']
    ServerDetailsCard: typeof import('./src/components/ServerDetailsCard.vue')['default']
    ServerStatusCard: typeof import('./src/components/ServerStatusCard.vue')['default']
  }
}
